Decode and verify UAA JWT tokens without connecting to UAA server
rabbitmq/rabbitmq-auth-backend-uaa pull request #5
Opened 2017-01-23 18:07 UTC by hairyhum

Fixes #3
Uses https://github.com/rabbitmq/uaa_jwt library to decode a token and verify a signature.
Signing keys should be predefined in the uaa_jwt application environment

2017-01-23 18:09 UTC, hairyhum commented
Using https://github.com/rabbitmq/rabbitmq-common/pull/161 packages Elixir dependencies and Elixir itself into `*.ez` archives.

2017-01-26 22:59 UTC, michaelklishin commented
This now has conflicts with master.

2017-01-27 11:49 UTC, hairyhum commented
Rebased from `master`

2017-02-01 16:28 UTC, kjnilsson requested changes

2017-02-01 16:28 UTC, kjnilsson commented on src/rabbit_auth_backend_uaa.erl
> +    case 'Elixir.UaaJWT':decode_and_verify(Token) of
Do we need to decode and verify the token each time? How about storing the decoded claims map in `impl` instead?

2017-02-01 16:28 UTC, kjnilsson commented on src/rabbit_auth_backend_uaa.erl
>  -define(HTTPC_OPTS, [{version, "HTTP/1.0"}]).
is this used? likewise `description()` below refers to HTTP

2017-02-16 13:13 UTC, kjnilsson requested changes
`make tests` fail unless `make dist` is first run.

2017-02-16 13:13 UTC, kjnilsson commented on src/rabbit_auth_backend_uaa.erl
> +check_vhost_access(#auth_user{username = Username, impl = DecodedToken},
`Username` is no longer used.

2017-02-16 16:01 UTC, hairyhum commented
`test-dist` now is built before tests are run:
https://github.com/rabbitmq/rabbitmq-common/commit/60f5bb2579735cc74cddfd8cfe70fc980c85faa5

2017-02-17 11:37 UTC, kjnilsson approved these changes

2017-02-17 11:37 UTC, merged